package repository

import (
	"context"
	"time"

	"github.com/partiri-cloud/message-in-a-bottle/internal/model"
	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"go.mongodb.org/mongo-driver/v2/mongo/options"
)

type TopicRepository struct {
	col *mongo.Collection
}

func NewTopicRepository(db *mongo.Database) *TopicRepository {
	return &TopicRepository{col: db.Collection("topics")}
}

func (r *TopicRepository) Create(ctx context.Context, topic *model.Topic) error {
	now := time.Now()
	topic.CreatedAt = now
	topic.UpdatedAt = now
	res, err := r.col.InsertOne(ctx, topic)
	if err != nil {
		return err
	}
	topic.ID = res.InsertedID.(bson.ObjectID)
	return nil
}

func (r *TopicRepository) FindByKey(ctx context.Context, envID bson.ObjectID, key string) (*model.Topic, error) {
	var topic model.Topic
	err := r.col.FindOne(ctx, bson.M{"environmentId": envID, "key": key}).Decode(&topic)
	if err != nil {
		return nil, err
	}
	return &topic, nil
}

func (r *TopicRepository) FindOrCreate(ctx context.Context, envID bson.ObjectID, key string) (*model.Topic, error) {
	topic, err := r.FindByKey(ctx, envID, key)
	if err == nil {
		return topic, nil
	}
	if err != mongo.ErrNoDocuments {
		return nil, err
	}
	topic = &model.Topic{
		EnvironmentID: envID,
		Key:           key,
		Name:          "Autogenerated-" + key,
	}
	if err := r.Create(ctx, topic); err != nil {
		// handle race condition: another request created it
		if mongo.IsDuplicateKeyError(err) {
			return r.FindByKey(ctx, envID, key)
		}
		return nil, err
	}
	return topic, nil
}

func (r *TopicRepository) FindMany(ctx context.Context, envID bson.ObjectID, keyPrefix string, page, limit int) ([]model.Topic, int64, error) {
	filter := bson.M{"environmentId": envID}
	if keyPrefix != "" {
		filter["key"] = bson.M{"$regex": "^" + keyPrefix}
	}

	total, err := r.col.CountDocuments(ctx, filter)
	if err != nil {
		return nil, 0, err
	}

	opts := options.Find().
		SetSkip(int64((page - 1) * limit)).
		SetLimit(int64(limit)).
		SetSort(bson.M{"createdAt": -1})

	cursor, err := r.col.Find(ctx, filter, opts)
	if err != nil {
		return nil, 0, err
	}
	defer cursor.Close(ctx)

	var topics []model.Topic
	if err := cursor.All(ctx, &topics); err != nil {
		return nil, 0, err
	}
	return topics, total, nil
}

func (r *TopicRepository) UpdateName(ctx context.Context, envID bson.ObjectID, key, name string) error {
	_, err := r.col.UpdateOne(ctx,
		bson.M{"environmentId": envID, "key": key},
		bson.M{"$set": bson.M{"name": name, "updatedAt": time.Now()}},
	)
	return err
}

func (r *TopicRepository) Delete(ctx context.Context, envID bson.ObjectID, key string) error {
	_, err := r.col.DeleteOne(ctx, bson.M{"environmentId": envID, "key": key})
	return err
}

func (r *TopicRepository) Collection() *mongo.Collection {
	return r.col
}
